### ISSUE TITLE
TODO - extract core

### ISSUE THREAD

**Issue by astahmer** [astahmer/box-extractor#11]
allow extracting values in a condition that is not a ternary (only those are supported atm, like `cond ? whenTrue : whenFalse`) : 
- [x] nullish coalescing operator: `valueOrNullable ?? fallback`
- [x] or operator: `valueOrFalsy || fallback`
- [x] and operator: `valueOrFalsy && fallback`
- [x] arrays (not really used by vanilla-extract except for responsiveArray but is not recommended, still could be useful for basically everyone else)

**Comment by astahmer** [comment]
https://github.com/astahmer/box-extractor/commit/d7aee9d4164d8a12bf5b161724470576afdb79dc

**Comment by astahmer** [comment]
[array](https://github.com/astahmer/box-extractor/commit/fa7a0a824f1adfdeb4700bbc4a6ecb55a5081353)
