### ISSUE TITLE
TODO - playwright tests for HMR on VE adapter plugin

### ISSUE THREAD

**Issue by astahmer** [astahmer/box-extractor#27]
it would be nice to have those integrations tests, just to be sure nothing breaks between releases since behaviours differs quite a lot

- [ ] CSR (classic SPA vite app)
- [ ] SSR (rakkas, vite-plugin-ssr, etc)
- [ ] HTML-only (rakkas with `rakkas({ filterRoutes: (_route) => "server" })` / vite-plugin-ssr with xxx.page.server.ts only =  no xxx.page.ts)

and each of those should test that:
- [ ] <Box color="xxx" /> has the "xxx" style on initial load
- [ ] <Box color="yyy" /> has the "yyy" style after HMR
- [ ] <Box color="yyy" /> has the updated "yyy" style when updating the sprinkle (`.css.ts`) providing this color+yyy combination

finally, it should test this for 3 different kind of sources : 
- [ ] `.css.ts` coming from user-code : `./src/sprinkle.css.ts`
- [ ] `.css.ts` coming from user-code in another package : `@monorepo/ui-lib`
- [ ] `.css.ts` coming from node_modules : `@npm-package/sprinkles`

**Comment by astahmer** [comment]
no need for it anymore since `@box-extractor/vanilla-wind` doesn't use sprinkles
